version: '3'
services:
    database:
        image: pasedb
        container_name: pasedb
        networks:
                pasedb_net:
                        ipv4_address: 10.10.10.10
                        aliases:
                                - pasedb
        tty: true
        stdin_open: true
        restart: always

    service:
        image: pasedbms
        container_name: pasedbms
        networks:
                pasedb_net:
                        ipv4_address: 10.10.10.20
                        aliases:
                                - pasedbms

    frontend:
        image: pasedbui
        container_name: pasedbui
        networks:
                pasedb_net:
                        ipv4_address: 10.10.10.30
        ports:
            - 80:8080
networks:
    pasedb_net:
        driver: bridge
        ipam:
            driver: default
            config: [{subnet: 10.10.10.0/24}]
