/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2018-06-19 18:34:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/menu.htm", Long.valueOf(1529264962000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html;charset=utf-8\" http-equiv=\"content-type\">\r\n");
      out.write("<title>Parental Alienation Support & Education Database [PASEDB]</title>\r\n");
      out.write("<link href=\"menu.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Persistant Header -->\r\n");
      out.write("<table style=\"width: 100%; text-align: right;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<ul class=\"pureCssMenu pureCssMenum\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\"><span>Members</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><![endif]-->\r\n");
      out.write("\t\t\t\t\t<ul class=\"pureCssMenum\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Reset Password</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!--[if lte IE 6]></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</a><![endif]--></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\">Comments</a></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\">Search</a></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\"><span>Support</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><![endif]-->\r\n");
      out.write("\t\t\t\t\t<ul class=\"pureCssMenum\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">All</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Facebook</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Facebook (Open)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Facebook (Closed)</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!--[if lte IE 6]></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</a><![endif]--></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\"><span>Legal</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><![endif]-->\r\n");
      out.write("\t\t\t\t\t<ul class=\"pureCssMenum\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Search</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">All Sites</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Supreme Court</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!--[if lte IE 6]></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</a><![endif]--></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\">In the Media</a></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\">Parental Rights</a></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\"><span>Parental \r\n");
      out.write("\t\t\tAlienation</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><![endif]-->\r\n");
      out.write("\t\t\t\t\t<ul class=\"pureCssMenum\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">PA &amp; PAS</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">DSM-5</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Tactics</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Fighting &amp; Prevention</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Effects</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"pureCssMenui\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pureCssMenui\" href=\"#\">Narcissism</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!--[if lte IE 6]></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</a><![endif]--></li>\r\n");
      out.write("\t\t\t<li class=\"pureCssMenui\"><a class=\"pureCssMenui\" href=\"#\">Home</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
