#!/bin/bash
cd /opt/pasedb
echo "... pulling new changes ..."
git pull

echo "... stopping docker container UI ..."
docker-compose stop ui

echo "... building new container ..."
./bootstrap

echo "... removing old container ..."
docker rm pasedbui

echo "... redeploysing newest build ..."
docker-compose up -d ui
