#!/bin/bash

cd pasedbui
docker-compose stop ui
docker-compose rm -f ui
mvn clean package
rm -f docker/paseadb.war
cp target/pasedb.war docker
cd docker
docker rmi pasedbui
docker build -t pasedbui .
cd ../../
docker-compose up -d ui
