#!/bin/bash

cwd=`pwd`
cd /opt/dev/pasedb/pasedbui

mvn clean package
cd /opt/dev/pasedb/
docker-compose stop ui

cd /opt/dev/pasedb/pasedbui/docker
docker rmi pasedbui
docker build -t pasedbui .

cd /opt/dev/pasedb/
docker-compose up -d --no-deps ui

# The --no-deps will not start linked services.

cd $cwd
