#!/bin/bash
cd mongodb
echo "attempting to stop mongo"
docker stop mongo
echo "attempting to remove pasedb:mongo"
docker rmi pasedb:mongo 
echo "attempting to build pasedb:mongo"
docker build -t pasedb:mongo .
echo "attempting to start pasedb:mongo on port 27017"
docker run -ti --rm --name mongo -p 27017:27017 -v /opt/pasedb/mongodb/db:/data/db2 pasedb:mongo
