#!/bin/bash

proj_dir="/opt/dev/pasedb"
cd $proj_dir

git fetch

if [ "$(git diff --name-only origin/develop | grep auto.deploy)" == "auto.deploy" ]; then
        echo "*** UPDATING PROJECT ***"
	echo ">>>> merging updates into develop <<<<"
        git pull origin develop

	echo ">>>> compiling new web-ui code <<<<"
	cd pasedbui
	mvn clean package

	rm -f docker/paseadb.war
	cp target/pasedb.war docker
	cd docker
#	docker rmi pasedbui
	docker build -t pasedbui .


	echo ">>>> docker-compose compile and bring online <<<<"
#	docker-compose build ui
#	docker stop ui
#	docker rm ui

cd $proj_dir
        echo "<<< Bringing down the website >>>"
	docker-compose down

        echo "<<< Bringing website back online >>>"
	docker-compose up

#	docker-compose up -d --no-deps ui

        echo "*** DEPLOYMENT COMPLETE ***"
        exit 1
else
        echo "project up-to-date, skipping auto.deploy"
        exit 1
fi


