#!/bin/bash

proj_dir="/opt/dev/pasedb"
cd $proj_dir

git fetch

if [ "$(git diff --name-only origin/develop | grep auto.deploy)" == "auto.deploy" ]; then
        echo "*** UPDATING PROJECT ***"
        git pull origin develop
        echo "... compile ..."
        echo "... docker build ..."
        echo "... docker redeploy ..."
#	docker-compose up -d --no-deps <service_name>
        echo "Deployment complete"
        exit 1
else
        echo "online"
        exit 1
fi


