FROM mongo:4.0.2

LABEL maintainer="Steve S Gee JR <ioexcept@gmail.com>"
LABEL description="PASEDB: Open Source Parental Alienation Support & Education DB schema loaders for mongodb 4.0.2"
LABEL url="http://pasedb.org"
LABEL version="2.7"

ADD . /tmp
