FROM mongo:4.0.2

LABEL maintainer="Steve S Gee JR <ioexcept@gmail.com>"
LABEL description="PASEDB: Open Source Parental Alienation Support & Education"
LABEL url="http://pasedb.org"
LABEL version="2.7"

ADD . /tmp
COPY counter.report /tmp/counter.report
