package org.pasedb.pasedbui;

import java.math.BigInteger;
import java.security.MessageDigest;

public class Utilities {

	public static String fetchMD5(String input) throws Exception {
		// Static getInstance method is called with hashing MD5
		MessageDigest md = MessageDigest.getInstance("MD5");

		// digest() method is called to calculate message digest
		// of an input digest() return array of byte
		byte[] messageDigest = md.digest(input.getBytes());

		// Convert byte array into signum representation
		BigInteger no = new BigInteger(1, messageDigest);

		// Convert message digest into hex value
		String hashtext = no.toString(16);
		while (hashtext.length() < 32) {
			hashtext = "0" + hashtext;
		}
		return hashtext;
	}

	public static void main(String args[]) {
		try {
			String s = "GeeksForGeeks"; 
			System.out.println("Your HashCode Generated by MD5 is: " + fetchMD5(s));
		}catch(Exception ex) {
			ex.printStackTrace();
		}
	}

}
